name: Backup
on:
  schedule:
    - cron: '30 10 * * *'  # Runs daily
  workflow_dispatch:      # Allows manual triggering
jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # THIS IS THE ONLY PERMISSION YOU NEED
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Backup website
        run: |
          DIR="backup"
          mkdir -p $DIR
          FILE="mini_$(date +'%y_%m_%d').json"
          rm -rf $DIR/$FILE
          cp -r docs/mini.json $DIR/$FILE
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "./$DIR"
          git diff --quiet && git diff --staged --quiet || git commit -m "Website backup"
          git push
